/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface StudySession {
  'startTime' : Time,
  'subject' : string,
  'endTime' : Time,
  'completed' : boolean,
}
export type Time = bigint;
export interface _SERVICE {
  'addSession' : ActorMethod<[string, Time, Time], undefined>,
  'calculateCompletionRate' : ActorMethod<[], bigint>,
  'completeSession' : ActorMethod<[string], undefined>,
  'getAllSessions' : ActorMethod<[], Array<StudySession>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];