/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const StudySession = IDL.Record({
  'startTime' : Time,
  'subject' : IDL.Text,
  'endTime' : Time,
  'completed' : IDL.Bool,
});

export const idlService = IDL.Service({
  'addSession' : IDL.Func([IDL.Text, Time, Time], [], []),
  'calculateCompletionRate' : IDL.Func([], [IDL.Nat], ['query']),
  'completeSession' : IDL.Func([IDL.Text], [], []),
  'getAllSessions' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const StudySession = IDL.Record({
    'startTime' : Time,
    'subject' : IDL.Text,
    'endTime' : Time,
    'completed' : IDL.Bool,
  });
  
  return IDL.Service({
    'addSession' : IDL.Func([IDL.Text, Time, Time], [], []),
    'calculateCompletionRate' : IDL.Func([], [IDL.Nat], ['query']),
    'completeSession' : IDL.Func([IDL.Text], [], []),
    'getAllSessions' : IDL.Func([], [IDL.Vec(StudySession)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };